[package]
name = "cli"
version = "1.0.0"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "CLI interface"
edition = "2018"

[dependencies]
utils = { path = "../utils" }
core = { path = "../core" }

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["yaml"]

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
