name: Security audit

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: omarabid-forks/rs-audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
